In [44]:
import os
import pandas as pd

path = os.path.abspath("/group/ag_abi/seiler/caroline_SRA/SRA_Search/timings")

In [39]:
row_list = []
for k in [19, 20]:
    for w in [24, 25, 26, 40, 41, 42, 43, 44]:
        filename = os.path.join(path, "k" + str(k) + "_" + "w" + str(w) + "_dna5.tsv")
        with open(filename, "r") as file:
            row_dict = {}
            row_dict["k"] = k
            row_dict["w"] = w
            for line in file:
                if line.startswith("Overall sequences"):
                    row_dict["Reads"] = line.split(':')[1].strip()
                elif line.startswith("Average HashTime per sequence:"):
                    row_dict["HashTime in ns per read"] = line.split(':')[1].strip()
                elif line.startswith("Average ThresholdTime per sequence:"):
                    row_dict["ThresholdTime in ns per read"] = line.split(':')[1].strip()
                else:
                    continue
            row_dict["Factor"] = "{0:.2f}".format(float(row_dict["ThresholdTime in ns per read"]) / float(row_dict["HashTime in ns per read"]))
            row_list.append(row_dict)

In [40]:
df = pd.DataFrame(row_list)

In [41]:
df = df[["k",
         "w", 
         "HashTime in ns per read", 
         "ThresholdTime in ns per read", 
         "Factor", 
         "Reads"]]

In [42]:
df

,k,w,HashTime in ns per read,ThresholdTime in ns per read,Factor,Reads
0,19,24,2959.79,4644.13,1.57,592615450
1,19,25,2963.69,4428.51,1.49,592615450
2,19,26,2981.03,4165.07,1.40,592615450
3,19,40,2724,2243.5,0.82,592615450
4,19,41,2703.27,2144.47,0.79,592615450
5,19,42,2692.95,2062.81,0.77,592615450
6,19,43,2672.61,2025.26,0.76,592615450
7,19,44,2684.97,1961.22,0.73,592615450
8,20,24,2934.52,4926.43,1.68,592615450
9,20,25,2956.72,4611.99,1.56,592615450
10,20,26,2968.33,4384.57,1.48,592615450
11,20,40,2923.43,2855.96,0.98,592615450
12,20,41,2926.18,2887.56,0.99,592615450
13,20,42,2933.09,3108.8,1.06,592615450
14,20,43,2906.8,3233.75,1.11,592615450
15,20,44,2928.21,3152.26,1.08,592615450

In [43]:
df.to_csv(os.path.join(path, "timings.tsv"), sep='\t', index=False)